### ISSUE TITLE
window.go SetupRenderWindow EnableDPI()

### ISSUE THREAD

**Issue by 5k3105** [felixangell/strife#6]
This call does not work on Windows 7. Commenting out the EnableDPI() call fixes the problem.

```go
panic: Failed to load Shcore.dll: The specified module could not be found.

goroutine 1 [running, locked to thread]:
syscall.(*LazyProc).mustFind(0xc042209140)
        C:/Go/src/syscall/dll_windows.go:280 +0x5f
syscall.(*LazyProc).Call(0xc042209140, 0xc0422185d8, 0x1, 0x1, 0x4b6197, 0xc042188180, 0x80, 0x34)
        C:/Go/src/syscall/dll_windows.go:301 +0x36
github.com/felixangell/strife.EnableDPI()
        C:/Users/xx/go/src/github.com/felixangell/strife/dpi_windows.go:30 +0x110
github.com/felixangell/strife.SetupRenderWindow(0x500, 0x2d0, 0xc0422185c0, 0x10)
        C:/Users/xx/go/src/github.com/felixangell/strife/window.go:183 +0x133
main.main()
        C:/Users/xx/go/src/github.com/felixangell/phi/main.go:85 +0xee
```

**Comment by felixangell** [comment]
Hey, thanks for reporting this. I've added some code which will catch the errors when loading the DLL. I'm hoping they would catch this, so there's a 50/50 chance my patch works.

Is there any chance you could give it a try and report back?

Otherwise I'll have to figure out if the OS is <= win 7 and error which is not ideal :frowning_face:

**Comment by 5k3105** [comment]
Looks like that fixed it. Thanks for the quick work :)

**Comment by felixangell** [comment]
@5k3105 Superb, thanks for posting the issue! :+1:
